kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: app
  source:
    repoURL: https://github.com/vidkazan/42iot-sample-app.git
    targetRevision: HEAD
    path: manifests
